CREATE TABLE DailyReminders(
    ReminderID INTEGER IDENTITY(1,1) PRIMARY KEY,
    UserID INTEGER NOT NULL UNIQUE FOREIGN KEY REFERENCES Users(UserID),
    ReminderTime VARCHAR(5) NOT NULL,
    Timezone NVARCHAR(64) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    LastSentDate DATE NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME NOT NULL DEFAULT GETUTCDATE()
);

CREATE INDEX IX_DailyReminders_Active ON DailyReminders(IsActive);
